# Generated by Django 3.1.1 on 2020-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='65b1cd952026edc5cc35', max_length=70)),
                ('google_analytics', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('google_tag_manager', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('google_optimize', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('google_ads', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('facebook_pixels', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mailchimp', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('modified_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='analytic',
            index=models.Index(fields=['reference', 'google_analytics'], name='analytics_a_referen_731f33_idx'),
        ),
    ]
