# Generated by Django 3.1.1 on 2020-10-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='reference',
            field=models.CharField(default='879a56bebd9f9217f799', max_length=70),
        ),
    ]
