# Generated by Django 3.1.1 on 2020-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='reference',
            field=models.CharField(default='10d636baa550df547eb9', max_length=70),
        ),
    ]
