# Generated by Django 3.1.1 on 2020-11-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20201026_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='reference',
            field=models.CharField(default='267a6a6f60b7b3fd7fdf', max_length=70),
        ),
    ]
