# Generated by Django 3.1.3 on 2020-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20201118_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='reference',
            field=models.CharField(default='f70c699628cd8d425da7', max_length=70),
        ),
    ]
