# Generated by Django 3.1.3 on 2020-11-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20201119_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='reference',
            field=models.CharField(default='440b013a4d9815905d95', max_length=70),
        ),
    ]
