# Generated by Django 3.1.3 on 2020-11-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20201119_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='reference',
            field=models.CharField(default='db7babce3a47f1939b75', max_length=70),
        ),
    ]
