version: 2.1

# orbs:
#   python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - "checkout"
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          command: |
            pipenv install
            pipenv shell
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          name: Running tests
          command: |
            python manage.py validate_templates
            python manage.py unreferenced_files
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app

workflows:
  main:
    jobs:
      # - build-and-test
      - build
