# Generated by Django 3.1.3 on 2020-11-19 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20201119_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('products', models.ManyToManyField(to='shop.Product')),
            ],
        ),
    ]
