# Generated by Django 3.1.1 on 2020-11-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='NAW1287G', max_length=10)),
                ('value', models.IntegerField(default=5)),
                ('value_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed amount', 'Fixed Amount'), ('free shipping', 'Free Shipping')], default='percentage', max_length=50)),
                ('on_entire_order', models.BooleanField(default=False, help_text='Apply on an entire order')),
                ('minimum_purchase', models.IntegerField(default=0)),
                ('minimum_quantity', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(default=0, help_text='Number of times a code can be used in total')),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, help_text='Apply on an entire collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.collection')),
                ('product', models.ForeignKey(blank=True, help_text='Apply on a specific product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
