# Generated by Django 3.1.4 on 2020-12-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(default='NAW4719U', max_length=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed amount', 'Fixed Amount'), ('free shipping', 'Free Shipping')], default='percentage', max_length=50),
        ),
    ]
