# Generated by Django 3.1.1 on 2020-09-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20200913_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(default='NAW8438O', max_length=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed amount', 'Fixed Amount'), ('free shipping', 'Free Shipping')], default='percentage', max_length=50),
        ),
    ]
