# Generated by Django 3.1.3 on 2020-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20201118_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(default='NAW1529Q', max_length=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed amount', 'Fixed Amount'), ('free shipping', 'Free Shipping')], default='percentage', max_length=50),
        ),
    ]
