# Generated by Django 3.1.1 on 2020-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_auto_20200914_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(default='NAW4198Y', max_length=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed amount', 'Fixed Amount'), ('free shipping', 'Free Shipping')], default='percentage', max_length=50),
        ),
    ]
