# Generated by Django 3.1.1 on 2020-11-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201120_1257'),
        ('store', '0002_auto_20201120_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoption',
            name='store_currency',
            field=models.CharField(choices=[('eur', 'Eur'), ('dollars', 'Dollars')], default='eur', max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_industry',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('clothing', 'Clothing'), ('jewelry', 'Jewelry')], default='Fashion', max_length=50),
        ),
    ]
