# Generated by Django 3.0.4 on 2020-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='presentation_text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
