# Generated by Django 3.0.4 on 2020-05-19 18:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='anonymouscart',
            managers=[
                ('anonymous_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('cart_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(limit_choices_to=3, to='shop.Image'),
        ),
    ]
