# Generated by Django 3.0.4 on 2020-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200521_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
