# Generated by Django 3.0.4 on 2020-05-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200519_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='order',
            new_name='customer_order',
        ),
    ]
