# Generated by Django 3.0.4 on 2020-05-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcollection_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
