# Generated by Django 3.0.4 on 2020-05-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200519_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='CustomerOrder',
        ),
    ]
