# Generated by Django 3.0.4 on 2020-05-21 12:28

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200521_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, validators=[shop.validators.quantity_validator]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[shop.validators.size_validator]),
        ),
    ]
