# Generated by Django 3.0.4 on 2020-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200519_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customer_order_id',
            field=models.CharField(default='zezoifenoz', max_length=20),
            preserve_default=False,
        ),
    ]
