# Generated by Django 3.0.4 on 2020-05-22 12:13

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200521_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_pct',
            field=models.IntegerField(default=0, validators=[shop.validators.discount_pct_validator]),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
