# Generated by Django 3.0.4 on 2020-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customerorder_customer_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='sac-en-daim'),
            preserve_default=False,
        ),
    ]
