# Generated by Django 3.0.4 on 2020-05-22 16:07

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200522_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-product__name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clothesize',
            name='name',
            field=models.CharField(max_length=3, validators=[shop.validators.size_validator]),
        ),
    ]
