# Generated by Django 3.0.4 on 2020-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_image_url'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='anonymouscart',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cart',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=3),
            preserve_default=False,
        ),
    ]
