# Generated by Django 3.0.4 on 2020-05-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200522_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.PromotionalCode'),
        ),
    ]
