# Generated by Django 3.0.4 on 2020-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200520_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=4)),
                ('end_date', models.DateField()),
                ('collection', models.ManyToManyField(blank=True, to='shop.Collection')),
                ('product', models.ManyToManyField(blank=True, to='shop.Product')),
            ],
        ),
    ]
