# Generated by Django 3.0.4 on 2020-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200522_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalcode',
            name='value',
            field=models.IntegerField(default=5),
        ),
    ]
