# Generated by Django 3.0.4 on 2020-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_promotionalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouscart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
