# Generated by Django 3.0.4 on 2020-05-22 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_promotionalcode_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customer_order_id',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='payment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='transaction_id',
            field=models.CharField(default='2c8a-5e12-5fdf-f2ed-0e7e-d99ddcfb203c40baf8b9fd0016e6553d4284855ce013157fa90396600a54c440', max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
