# Generated by Django 3.0.4 on 2020-05-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200520_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='anonymous_cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AnonymousCart',
        ),
    ]
