# Generated by Django 3.0.4 on 2020-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200520_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
            preserve_default=False,
        ),
    ]
