# Generated by Django 3.0.4 on 2020-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200522_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='reference',
            field=models.CharField(default='inozienozin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='transaction',
            field=models.CharField(default='61fa-db40-e010-6324-def2-d99ddcfb203c40baf8b9fd0016e6553d4284855ce013157fa90396600a54c440', max_length=200),
        ),
    ]
