# Generated by Django 3.0.4 on 2020-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cart_price_ht'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['price_ht'], name='shop_cart_price_h_e50c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['url'], name='shop_image_url_972fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['collection'], name='shop_produc_collect_8dfb86_idx'),
        ),
    ]
