# Generated by Django 3.0.4 on 2020-05-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200523_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='transaction',
            field=models.CharField(default='3e35-ec35-67b9-ec3b-b6d7-d99ddcfb203c40baf8b9fd0016e6553d4284855ce013157fa90396600a54c440', max_length=200),
        ),
    ]
