# Generated by Django 3.0.4 on 2020-05-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200520_1808'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='shop_cart_price_h_e50c8d_idx',
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['price_ht', 'quantity'], name='shop_cart_price_h_37ab93_idx'),
        ),
    ]
