# Generated by Django 3.0.4 on 2020-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200523_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='transaction',
            field=models.CharField(default='1870-1a03-5905-170c-e927-d99ddcfb203c40baf8b9fd0016e6553d4284855ce013157fa90396600a54c440', max_length=200),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['payment'], name='shop_custom_payment_49b892_idx'),
        ),
    ]
