# Generated by Django 3.0.4 on 2020-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200523_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='transaction',
            field=models.CharField(default='ee1f-d99ddcfb203c40baf8b9fd0016e6553d4284855ce013157fa90396600a54c440', max_length=200),
        ),
    ]
