# Generated by Django 3.0.4 on 2020-05-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200523_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='transaction',
            field=models.CharField(default='a29d-d99ddcfb203c40baf8b9fd0016e6553d4284855ce013157fa90396600a54c440', max_length=200),
        ),
    ]
