# Generated by Django 3.0.4 on 2020-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200524_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('femme', 'Femme'), ('homme', 'Homme')], default='femme', max_length=50),
        ),
        migrations.AddField(
            model_name='promotionalcode',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='transaction',
            field=models.CharField(default='676e-d99ddcfb203c40baf8b9fd0016e6553d4284855ce013157fa90396600a54c440', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
