# Generated by Django 3.1.1 on 2020-09-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuserprofile',
            old_name='stripe_id',
            new_name='stripe_customer_id',
        ),
    ]
