# Generated by Django 3.0.8 on 2020-08-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200831_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='surname',
            new_name='lastname',
        ),
    ]
