# Generated by Django 3.1.1 on 2020-09-23 15:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('cart_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_price_h_6cbfe4_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price_ttc',
        ),
        migrations.AddField(
            model_name='cart',
            name='price_post_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price including taxes'),
        ),
        migrations.AddField(
            model_name='cart',
            name='price_pre_tax',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=5, verbose_name='Price excluding taxes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='delivery',
            field=models.CharField(choices=[('standard', 'Standard')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='transaction',
            field=models.CharField(default='f702-911cac229bca39e61862e83a0298049433b81a205c92771b37fbfcddf24d0a07', max_length=200),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['price_pre_tax', 'quantity'], name='cart_cart_price_p_adbea5_idx'),
        ),
    ]
