# Generated by Django 3.1.3 on 2020-11-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201119_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='delivery',
            field=models.CharField(choices=[('standard', 'Standard')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='transaction',
            field=models.CharField(default='1fa2-911cac229bca39e61862e83a0298049433b81a205c92771b37fbfcddf24d0a07', max_length=200),
        ),
    ]
