# Generated by Django 3.1.1 on 2020-09-13 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=100)),
                ('customer_care_email', models.EmailField(max_length=100)),
                ('legal_name', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('store_currency', models.CharField(choices=[('eur', 'Eur'), ('dollars', 'Dollars')], default='eur', max_length=10)),
                ('tax_rate', models.IntegerField(default=20)),
                ('automatic_archive', models.BooleanField(default=False, help_text='Archive an order automatically after it has been fulfilled and paid')),
                ('google_analytics', models.CharField(blank=True, max_length=50, null=True)),
                ('google_tag_manager', models.CharField(blank=True, max_length=50, null=True)),
                ('google_optimize', models.CharField(blank=True, max_length=50, null=True)),
                ('google_ads', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_pixels', models.CharField(blank=True, max_length=50, null=True)),
                ('mailchimp', models.CharField(blank=True, max_length=50, null=True)),
                ('allow_coupons', models.BooleanField(default=False)),
                ('allow_accounts', models.BooleanField(default=False)),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
